//! Flutter-facing API surface (generated by `flutter_rust_bridge`).
//!
//! The app links this crate directly, so everything here runs in-process: no
//! HTTP, no WebSocket, no JSON round trip. The REST/WS DTOs in
//! [`crate::models`] still exist for the optional HTTP front-end, but the
//! Flutter client only sees the shared contract types below.
//!
//! The contract itself lives here rather than in a separate crate because FRB
//! generates *value* types only for structs and enums defined inside the
//! scanned crate; a re-exported type becomes an opaque Rust handle instead.

pub mod bridge_models;
pub mod library;
pub mod online;
pub mod player;
