// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::uninlined_format_args,
    clippy::needless_borrow,
    mismatched_lifetime_syntaxes
)]

// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
                    default_stream_sink_codec = SseCodec,
                    default_rust_opaque = RustOpaqueMoi,
                    default_rust_auto_opaque = RustAutoOpaqueMoi,
                );
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.13.0";
                pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1533674464;
            

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__player__command_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "command", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_command = <crate::api::bridge_models::BridgePlayerCommand>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::player::command(api_command)?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__library__engine_name_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "engine_name", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::library::engine_name()?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__player__init_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "init", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_music_dir = <Option<String>>::sse_decode(&mut deserializer);
let api_volume = <f64>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::player::init(api_music_dir, api_volume)?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__library__playlist_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "playlist", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::library::playlist()?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__online__prepare_track_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "prepare_track", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_track_id = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::online::prepare_track(api_track_id)?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__library__search_songs_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "search_songs", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_query = <String>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::library::search_songs(api_query)?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__online__search_videos_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "search_videos", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_query = <String>::sse_decode(&mut deserializer);
let api_page = <u32>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::online::search_videos(api_query, api_page)?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__player__snapshot_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "snapshot", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::player::snapshot()?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__online__status_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "status", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end(); move |context|  {
                    transform_result_sse::<_, ()>((move ||  {
                         let output_ok = Ok::<_, ()>(crate::api::online::status())?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }fn wire__crate__api__player__subscribe_impl(port_: flutter_rust_bridge::for_generated::MessagePort,ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,rust_vec_len_: i32,data_len_: i32)  {
                FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec,_,_>(flutter_rust_bridge::for_generated::TaskInfo{ debug_name: "subscribe", port: Some(port_), mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal }, move || {
            let message = unsafe { flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(ptr_, rust_vec_len_, data_len_) };
            let mut deserializer = flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<crate::api::bridge_models::BridgePlayerSnapshot,flutter_rust_bridge::for_generated::SseCodec>>::sse_decode(&mut deserializer);deserializer.end(); move |context|  {
                    transform_result_sse::<_, String>((move ||  {
                         let output_ok = crate::api::player::subscribe(api_sink)?;   std::result::Result::Ok(output_ok)
                    })())
                } })
            }

// Section: dart2rust


                impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);}
                }
                
                impl SseDecode for StreamSink<crate::api::bridge_models::BridgePlayerSnapshot,flutter_rust_bridge::for_generated::SseCodec> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);}
                }
                
                impl SseDecode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();}
                }
                
                impl SseDecode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap() != 0}
                }
                
                impl SseDecode for crate::api::online::BridgeOnlineStatus {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_available = <bool>::sse_decode(deserializer);
let mut var_authenticated = <bool>::sse_decode(deserializer);
let mut var_cacheDir = <Option<String>>::sse_decode(deserializer);
let mut var_error = <Option<String>>::sse_decode(deserializer);
return crate::api::online::BridgeOnlineStatus{available: var_available, authenticated: var_authenticated, cache_dir: var_cacheDir, error: var_error};}
                }
                
                impl SseDecode for crate::api::bridge_models::BridgePlaybackStatus {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::bridge_models::BridgePlaybackStatus::Idle,
1 => crate::api::bridge_models::BridgePlaybackStatus::Loading,
2 => crate::api::bridge_models::BridgePlaybackStatus::Playing,
3 => crate::api::bridge_models::BridgePlaybackStatus::Paused,
4 => crate::api::bridge_models::BridgePlaybackStatus::Buffering,
5 => crate::api::bridge_models::BridgePlaybackStatus::Error,
            _ => unreachable!("Invalid variant for BridgePlaybackStatus: {}", inner),
        };}
                }
                
                impl SseDecode for crate::api::bridge_models::BridgePlayerCommand {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut tag_ = <i32>::sse_decode(deserializer);
            match tag_ {0 => { let mut var_trackId = <String>::sse_decode(deserializer);
return crate::api::bridge_models::BridgePlayerCommand::Play{track_id: var_trackId}; }
1 => { let mut var_track = <crate::api::bridge_models::BridgeTrack>::sse_decode(deserializer);
return crate::api::bridge_models::BridgePlayerCommand::PlayTrack{track: var_track}; }
2 => { let mut var_tracks = <Vec<crate::api::bridge_models::BridgeTrack>>::sse_decode(deserializer);
let mut var_startIndex = <i32>::sse_decode(deserializer);
return crate::api::bridge_models::BridgePlayerCommand::PlayQueue{tracks: var_tracks, start_index: var_startIndex}; }
3 => { return crate::api::bridge_models::BridgePlayerCommand::Pause; }
4 => { return crate::api::bridge_models::BridgePlayerCommand::Resume; }
5 => { return crate::api::bridge_models::BridgePlayerCommand::Toggle; }
6 => { return crate::api::bridge_models::BridgePlayerCommand::Next; }
7 => { return crate::api::bridge_models::BridgePlayerCommand::Previous; }
8 => { let mut var_positionMs = <i64>::sse_decode(deserializer);
return crate::api::bridge_models::BridgePlayerCommand::Seek{position_ms: var_positionMs}; }
9 => { let mut var_volume = <f64>::sse_decode(deserializer);
return crate::api::bridge_models::BridgePlayerCommand::SetVolume{volume: var_volume}; }
10 => { let mut var_enabled = <bool>::sse_decode(deserializer);
return crate::api::bridge_models::BridgePlayerCommand::SetShuffle{enabled: var_enabled}; }
11 => { let mut var_mode = <crate::api::bridge_models::BridgeRepeatMode>::sse_decode(deserializer);
return crate::api::bridge_models::BridgePlayerCommand::SetRepeat{mode: var_mode}; }
12 => { return crate::api::bridge_models::BridgePlayerCommand::ClearQueue; }
13 => { return crate::api::bridge_models::BridgePlayerCommand::RequestSnapshot; }
 _ => { unimplemented!(""); }}}
                }
                
                impl SseDecode for crate::api::bridge_models::BridgePlayerSnapshot {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_currentTrack = <Option<crate::api::bridge_models::BridgeTrack>>::sse_decode(deserializer);
let mut var_status = <crate::api::bridge_models::BridgePlaybackStatus>::sse_decode(deserializer);
let mut var_positionMs = <i64>::sse_decode(deserializer);
let mut var_durationMs = <i64>::sse_decode(deserializer);
let mut var_volume = <f64>::sse_decode(deserializer);
let mut var_isShuffle = <bool>::sse_decode(deserializer);
let mut var_repeatMode = <crate::api::bridge_models::BridgeRepeatMode>::sse_decode(deserializer);
let mut var_queue = <Vec<crate::api::bridge_models::BridgeTrack>>::sse_decode(deserializer);
let mut var_currentIndex = <i32>::sse_decode(deserializer);
let mut var_updatedAtMs = <i64>::sse_decode(deserializer);
return crate::api::bridge_models::BridgePlayerSnapshot{current_track: var_currentTrack, status: var_status, position_ms: var_positionMs, duration_ms: var_durationMs, volume: var_volume, is_shuffle: var_isShuffle, repeat_mode: var_repeatMode, queue: var_queue, current_index: var_currentIndex, updated_at_ms: var_updatedAtMs};}
                }
                
                impl SseDecode for crate::api::bridge_models::BridgeRepeatMode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::bridge_models::BridgeRepeatMode::Off,
1 => crate::api::bridge_models::BridgeRepeatMode::All,
2 => crate::api::bridge_models::BridgeRepeatMode::One,
            _ => unreachable!("Invalid variant for BridgeRepeatMode: {}", inner),
        };}
                }
                
                impl SseDecode for crate::api::bridge_models::BridgeTrack {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut var_id = <String>::sse_decode(deserializer);
let mut var_title = <String>::sse_decode(deserializer);
let mut var_artist = <String>::sse_decode(deserializer);
let mut var_album = <String>::sse_decode(deserializer);
let mut var_coverUrl = <Option<String>>::sse_decode(deserializer);
let mut var_durationMs = <i64>::sse_decode(deserializer);
let mut var_source = <crate::api::bridge_models::BridgeTrackSource>::sse_decode(deserializer);
return crate::api::bridge_models::BridgeTrack{id: var_id, title: var_title, artist: var_artist, album: var_album, cover_url: var_coverUrl, duration_ms: var_durationMs, source: var_source};}
                }
                
                impl SseDecode for crate::api::bridge_models::BridgeTrackSource {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::bridge_models::BridgeTrackSource::Local,
1 => crate::api::bridge_models::BridgeTrackSource::Remote,
2 => crate::api::bridge_models::BridgeTrackSource::Mock,
3 => crate::api::bridge_models::BridgeTrackSource::Unknown,
            _ => unreachable!("Invalid variant for BridgeTrackSource: {}", inner),
        };}
                }
                
                impl SseDecode for f64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_f64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_i64::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for Vec<crate::api::bridge_models::BridgeTrack> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ { ans_.push(<crate::api::bridge_models::BridgeTrack>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = Vec::with_capacity(len_ as usize);
        for idx_ in 0..len_ { ans_.push(<u8>::sse_decode(deserializer)); }
        return ans_;}
                }
                
                impl SseDecode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<String>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for Option<crate::api::bridge_models::BridgeTrack> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {if (<bool>::sse_decode(deserializer)) {
                return Some(<crate::api::bridge_models::BridgeTrack>::sse_decode(deserializer));
            } else {
                return None;
            }}
                }
                
                impl SseDecode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u32::<NativeEndian>().unwrap()}
                }
                
                impl SseDecode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {deserializer.cursor.read_u8().unwrap()}
                }
                
                impl SseDecode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
                }
                
                fn pde_ffi_dispatcher_primary_impl(
                    func_id: i32,port: flutter_rust_bridge::for_generated::MessagePort,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                )  {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        1 => wire__crate__api__player__command_impl(port, ptr, rust_vec_len, data_len),
2 => wire__crate__api__library__engine_name_impl(port, ptr, rust_vec_len, data_len),
3 => wire__crate__api__player__init_impl(port, ptr, rust_vec_len, data_len),
4 => wire__crate__api__library__playlist_impl(port, ptr, rust_vec_len, data_len),
5 => wire__crate__api__online__prepare_track_impl(port, ptr, rust_vec_len, data_len),
6 => wire__crate__api__library__search_songs_impl(port, ptr, rust_vec_len, data_len),
7 => wire__crate__api__online__search_videos_impl(port, ptr, rust_vec_len, data_len),
8 => wire__crate__api__player__snapshot_impl(port, ptr, rust_vec_len, data_len),
9 => wire__crate__api__online__status_impl(port, ptr, rust_vec_len, data_len),
10 => wire__crate__api__player__subscribe_impl(port, ptr, rust_vec_len, data_len),
                        _ => unreachable!(),
                    }
                }
                
                fn pde_ffi_dispatcher_sync_impl(
                    func_id: i32,
                    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
                    rust_vec_len: i32,
                    data_len: i32,
                ) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
                    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
                    match func_id {
                        
                        _ => unreachable!(),
                    }
                }
                

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::online::BridgeOnlineStatus {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.available.into_into_dart().into_dart(),
self.authenticated.into_into_dart().into_dart(),
self.cache_dir.into_into_dart().into_dart(),
self.error.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::online::BridgeOnlineStatus {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::online::BridgeOnlineStatus> for crate::api::online::BridgeOnlineStatus {
            fn into_into_dart(self) -> crate::api::online::BridgeOnlineStatus {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::bridge_models::BridgePlaybackStatus {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Idle => 0.into_dart(),
Self::Loading => 1.into_dart(),
Self::Playing => 2.into_dart(),
Self::Paused => 3.into_dart(),
Self::Buffering => 4.into_dart(),
Self::Error => 5.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::bridge_models::BridgePlaybackStatus {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge_models::BridgePlaybackStatus> for crate::api::bridge_models::BridgePlaybackStatus {
            fn into_into_dart(self) -> crate::api::bridge_models::BridgePlaybackStatus {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::bridge_models::BridgePlayerCommand {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {crate::api::bridge_models::BridgePlayerCommand::Play{track_id} => { [0.into_dart(),
track_id.into_into_dart().into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::PlayTrack{track} => { [1.into_dart(),
track.into_into_dart().into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::PlayQueue{tracks,start_index} => { [2.into_dart(),
tracks.into_into_dart().into_dart(),
start_index.into_into_dart().into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::Pause => { [3.into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::Resume => { [4.into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::Toggle => { [5.into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::Next => { [6.into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::Previous => { [7.into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::Seek{position_ms} => { [8.into_dart(),
position_ms.into_into_dart().into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::SetVolume{volume} => { [9.into_dart(),
volume.into_into_dart().into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::SetShuffle{enabled} => { [10.into_dart(),
enabled.into_into_dart().into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::SetRepeat{mode} => { [11.into_dart(),
mode.into_into_dart().into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::ClearQueue => { [12.into_dart()].into_dart() }
crate::api::bridge_models::BridgePlayerCommand::RequestSnapshot => { [13.into_dart()].into_dart() }
 _ => { unimplemented!(""); }}
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::bridge_models::BridgePlayerCommand {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge_models::BridgePlayerCommand> for crate::api::bridge_models::BridgePlayerCommand {
            fn into_into_dart(self) -> crate::api::bridge_models::BridgePlayerCommand {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::bridge_models::BridgePlayerSnapshot {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.current_track.into_into_dart().into_dart(),
self.status.into_into_dart().into_dart(),
self.position_ms.into_into_dart().into_dart(),
self.duration_ms.into_into_dart().into_dart(),
self.volume.into_into_dart().into_dart(),
self.is_shuffle.into_into_dart().into_dart(),
self.repeat_mode.into_into_dart().into_dart(),
self.queue.into_into_dart().into_dart(),
self.current_index.into_into_dart().into_dart(),
self.updated_at_ms.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::bridge_models::BridgePlayerSnapshot {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge_models::BridgePlayerSnapshot> for crate::api::bridge_models::BridgePlayerSnapshot {
            fn into_into_dart(self) -> crate::api::bridge_models::BridgePlayerSnapshot {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::bridge_models::BridgeRepeatMode {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Off => 0.into_dart(),
Self::All => 1.into_dart(),
Self::One => 2.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::bridge_models::BridgeRepeatMode {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge_models::BridgeRepeatMode> for crate::api::bridge_models::BridgeRepeatMode {
            fn into_into_dart(self) -> crate::api::bridge_models::BridgeRepeatMode {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::bridge_models::BridgeTrack {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    [
                    self.id.into_into_dart().into_dart(),
self.title.into_into_dart().into_dart(),
self.artist.into_into_dart().into_dart(),
self.album.into_into_dart().into_dart(),
self.cover_url.into_into_dart().into_dart(),
self.duration_ms.into_into_dart().into_dart(),
self.source.into_into_dart().into_dart()
                ].into_dart()
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::bridge_models::BridgeTrack {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge_models::BridgeTrack> for crate::api::bridge_models::BridgeTrack {
            fn into_into_dart(self) -> crate::api::bridge_models::BridgeTrack {
                self
            }
        }
// Codec=Dco (DartCObject based), see doc to use other codecs
            impl flutter_rust_bridge::IntoDart for crate::api::bridge_models::BridgeTrackSource {
                fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
                    match self {
                    Self::Local => 0.into_dart(),
Self::Remote => 1.into_dart(),
Self::Mock => 2.into_dart(),
Self::Unknown => 3.into_dart(),
                    _ => unreachable!(),
                }
                }
            }
            impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::bridge_models::BridgeTrackSource {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::bridge_models::BridgeTrackSource> for crate::api::bridge_models::BridgeTrackSource {
            fn into_into_dart(self) -> crate::api::bridge_models::BridgeTrackSource {
                self
            }
        }

                impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(format!("{:?}", self), serializer);}
                }
                
                impl SseEncode for StreamSink<crate::api::bridge_models::BridgePlayerSnapshot,flutter_rust_bridge::for_generated::SseCodec> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {unimplemented!("")}
                }
                
                impl SseEncode for String {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Vec<u8>>::sse_encode(self.into_bytes(), serializer);}
                }
                
                impl SseEncode for bool {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self as _).unwrap();}
                }
                
                impl SseEncode for crate::api::online::BridgeOnlineStatus {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.available, serializer);
<bool>::sse_encode(self.authenticated, serializer);
<Option<String>>::sse_encode(self.cache_dir, serializer);
<Option<String>>::sse_encode(self.error, serializer);}
                }
                
                impl SseEncode for crate::api::bridge_models::BridgePlaybackStatus {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::api::bridge_models::BridgePlaybackStatus::Idle => { 0 }
crate::api::bridge_models::BridgePlaybackStatus::Loading => { 1 }
crate::api::bridge_models::BridgePlaybackStatus::Playing => { 2 }
crate::api::bridge_models::BridgePlaybackStatus::Paused => { 3 }
crate::api::bridge_models::BridgePlaybackStatus::Buffering => { 4 }
crate::api::bridge_models::BridgePlaybackStatus::Error => { 5 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for crate::api::bridge_models::BridgePlayerCommand {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {match self {crate::api::bridge_models::BridgePlayerCommand::Play{track_id} => { <i32>::sse_encode(0, serializer); <String>::sse_encode(track_id, serializer);
 }
crate::api::bridge_models::BridgePlayerCommand::PlayTrack{track} => { <i32>::sse_encode(1, serializer); <crate::api::bridge_models::BridgeTrack>::sse_encode(track, serializer);
 }
crate::api::bridge_models::BridgePlayerCommand::PlayQueue{tracks,start_index} => { <i32>::sse_encode(2, serializer); <Vec<crate::api::bridge_models::BridgeTrack>>::sse_encode(tracks, serializer);
<i32>::sse_encode(start_index, serializer);
 }
crate::api::bridge_models::BridgePlayerCommand::Pause => { <i32>::sse_encode(3, serializer);  }
crate::api::bridge_models::BridgePlayerCommand::Resume => { <i32>::sse_encode(4, serializer);  }
crate::api::bridge_models::BridgePlayerCommand::Toggle => { <i32>::sse_encode(5, serializer);  }
crate::api::bridge_models::BridgePlayerCommand::Next => { <i32>::sse_encode(6, serializer);  }
crate::api::bridge_models::BridgePlayerCommand::Previous => { <i32>::sse_encode(7, serializer);  }
crate::api::bridge_models::BridgePlayerCommand::Seek{position_ms} => { <i32>::sse_encode(8, serializer); <i64>::sse_encode(position_ms, serializer);
 }
crate::api::bridge_models::BridgePlayerCommand::SetVolume{volume} => { <i32>::sse_encode(9, serializer); <f64>::sse_encode(volume, serializer);
 }
crate::api::bridge_models::BridgePlayerCommand::SetShuffle{enabled} => { <i32>::sse_encode(10, serializer); <bool>::sse_encode(enabled, serializer);
 }
crate::api::bridge_models::BridgePlayerCommand::SetRepeat{mode} => { <i32>::sse_encode(11, serializer); <crate::api::bridge_models::BridgeRepeatMode>::sse_encode(mode, serializer);
 }
crate::api::bridge_models::BridgePlayerCommand::ClearQueue => { <i32>::sse_encode(12, serializer);  }
crate::api::bridge_models::BridgePlayerCommand::RequestSnapshot => { <i32>::sse_encode(13, serializer);  }
 _ => { unimplemented!(""); }}}
                }
                
                impl SseEncode for crate::api::bridge_models::BridgePlayerSnapshot {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<Option<crate::api::bridge_models::BridgeTrack>>::sse_encode(self.current_track, serializer);
<crate::api::bridge_models::BridgePlaybackStatus>::sse_encode(self.status, serializer);
<i64>::sse_encode(self.position_ms, serializer);
<i64>::sse_encode(self.duration_ms, serializer);
<f64>::sse_encode(self.volume, serializer);
<bool>::sse_encode(self.is_shuffle, serializer);
<crate::api::bridge_models::BridgeRepeatMode>::sse_encode(self.repeat_mode, serializer);
<Vec<crate::api::bridge_models::BridgeTrack>>::sse_encode(self.queue, serializer);
<i32>::sse_encode(self.current_index, serializer);
<i64>::sse_encode(self.updated_at_ms, serializer);}
                }
                
                impl SseEncode for crate::api::bridge_models::BridgeRepeatMode {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::api::bridge_models::BridgeRepeatMode::Off => { 0 }
crate::api::bridge_models::BridgeRepeatMode::All => { 1 }
crate::api::bridge_models::BridgeRepeatMode::One => { 2 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for crate::api::bridge_models::BridgeTrack {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<String>::sse_encode(self.id, serializer);
<String>::sse_encode(self.title, serializer);
<String>::sse_encode(self.artist, serializer);
<String>::sse_encode(self.album, serializer);
<Option<String>>::sse_encode(self.cover_url, serializer);
<i64>::sse_encode(self.duration_ms, serializer);
<crate::api::bridge_models::BridgeTrackSource>::sse_encode(self.source, serializer);}
                }
                
                impl SseEncode for crate::api::bridge_models::BridgeTrackSource {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(match self {crate::api::bridge_models::BridgeTrackSource::Local => { 0 }
crate::api::bridge_models::BridgeTrackSource::Remote => { 1 }
crate::api::bridge_models::BridgeTrackSource::Mock => { 2 }
crate::api::bridge_models::BridgeTrackSource::Unknown => { 3 }
 _ => { unimplemented!(""); }}, serializer);}
                }
                
                impl SseEncode for f64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_f64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for i32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for i64 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_i64::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for Vec<crate::api::bridge_models::BridgeTrack> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <crate::api::bridge_models::BridgeTrack>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Vec<u8> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<i32>::sse_encode(self.len() as _, serializer);
        for item in self { <u8>::sse_encode(item, serializer); }}
                }
                
                impl SseEncode for Option<String> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <String>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for Option<crate::api::bridge_models::BridgeTrack> {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {<bool>::sse_encode(self.is_some(), serializer);
                if let Some(value) = self {
                    <crate::api::bridge_models::BridgeTrack>::sse_encode(value, serializer);
                }}
                }
                
                impl SseEncode for u32 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u32::<NativeEndian>(self).unwrap();}
                }
                
                impl SseEncode for u8 {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {serializer.cursor.write_u8(self).unwrap();}
                }
                
                impl SseEncode for () {
                    // Codec=Sse (Serialization based), see doc to use other codecs
                    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
                }
                


        
        
        #[cfg(not(target_family = "wasm"))]
        mod io {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_io!();


        }
        #[cfg(not(target_family = "wasm"))]
        pub use io::*;
        
        
        /// cbindgen:ignore
        #[cfg(target_family = "wasm")]
        mod web {
            // This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.



// Section: imports

use flutter_rust_bridge::{Handler, IntoIntoDart};
use flutter_rust_bridge::for_generated::{Lockable, transform_result_dco, Lifetimeable};
use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, WriteBytesExt, ReadBytesExt};use super::*;
                use flutter_rust_bridge::for_generated::wasm_bindgen;
                use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;


// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate_web!();


        }
        #[cfg(target_family = "wasm")]
        pub use web::*;
        